name: issue-workflow
on:
  issues:
    types: [opens]

jobs:
  issue_job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world
    - name: step2
      run: |
        echo hello issue